### ISSUE TITLE
关于定位结果的一些疑问

### ISSUE THREAD

**Issue by Erika1kuta** [XikunLiu-huskit/GLIO#8]
非常感谢您的分享和工作，
我想请问一下: Urbannav的文章中使用了LIO-SAM对于TST和Whampoa数据集进行了评估，结果如下
![image](https://github.com/XikunLiu-huskit/GLIO/assets/138324921/ed9779b9-9263-408d-8417-6237079bb411)
然后您的文章中使用LIO-GNSS表示了LIO-SAM和gnss的融合结果（不太确定我理解的是不是对的），
![glio_tst_eval](https://github.com/XikunLiu-huskit/GLIO/assets/138324921/1dbff019-1b5a-4d1e-b8a8-abd4523f9deb)
![2024-06-09_19-05](https://github.com/XikunLiu-huskit/GLIO/assets/138324921/ba6cee99-1e24-455d-890a-a92c63f653a7)
但该方法还有您提出的方法好像效果都没有纯LIO系统好，对于这些环境添加GNSS信息反而成了干扰吗？我不确定是不是我搞错了评估标准，有些地方也没有太弄明白，期待您的解答。

**Comment by XikunLiu-huskit** [comment]
Hi @Erika1kuta , thank you for the interest. The UrbanNav paper states that "The relative positioning errors (RPEs) of the LOAM and LIO-SAM are evaluated using the EVO toolkit", which means that the UrbanNav paper used RPEs rather than absolute positioning errors (APEs) to evaluate the results, whereas the results in the GLIO paper were evaluated using APEs. So there will be a difference.

**Comment by Erika1kuta** [comment]
Thank you for the reply. I appreciate your help.
